server:
  port: 8080

pinterest:
  loginUrl: https://www.pinterest.com/login
  email: PINTEREST_EMAIL
  password: PINTEREST_PASSWORD

proxy:
  socksProxy: SOCKS_PROXY
  proxyUsername: PROXY_USERNAME
  proxyPassword: PROXY_PASSWORD

spring.resources.static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/