server:
  port: 8080

pinterest:
  loginUrl: https://www.pinterest.com/login
  email: tomislav.kos.grabar@gmail.com
  password: kos373EV

spring.resources.static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/